# Generated by Django 5.1.3 on 2024-11-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(default='IN(PS PI)/OUT(SC GD)', max_length=10),
        ),
    ]
