# Generated by Django 5.1.3 on 2024-11-26 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_customer_total_sale_supplier_total_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_sale',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='total_purchase',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
