# Generated by Django 5.1.3 on 2024-11-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_customer_total_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(choices=[], default='IN(PS PI)/OUT(SC GD)', max_length=10),
        ),
    ]
