# Generated by Django 5.1.3 on 2024-11-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_transaction_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(choices=[('G', 'General')], max_length=10),
        ),
    ]
