# Generated by Django 5.1.3 on 2024-11-29 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='total_purchase',
            new_name='total_sale',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='triaaal',
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(),
        ),
    ]
